### ISSUE TITLE
SushiJS London

### ISSUE THREAD

**Issue by andrew** [sushijs/meta#1]
I love :sushi: and know a little JavaScript, we should make this happen!

cc @orliesaurus @basicallydan

**Comment by basicallydan** [comment]
Happy to help here in the UK. I'm in London

**Comment by andrew** [comment]
@basicallydan excellent, let's move the discussion over here: https://github.com/sushijs/london-uk/issues/1

**Comment by terinjokes** [comment]
One last thing that's probably best to address here: who should I be coordinating with?

**Comment by andrew** [comment]
I don't mind co-ordinating, unless @basicallydan wants to do it?
