### ISSUE TITLE
Sydney SushiJS

### ISSUE THREAD

**Issue by export-mike** [sushijs/meta#14]
Hi I'm a brit now in Sydney, I'd like to continue the legendary eat-up in Sydney! I need sushi and javascript.

@clarkie @graycodes What's up!?

**Comment by terinjokes** [comment]
@export-mike I can definitely make the repo for you. 🍣 

Do you have an idea where in Sydney?

**Comment by export-mike** [comment]
@terinjokes not sure yet! Go for where's convienient for the majority

**Comment by export-mike** [comment]
@terinjokes did you send me an invite to the repo? :) excited to get this started :D thanks,

**Comment by graycodes** [comment]
Will the sushi be upside down?

**Comment by terinjokes** [comment]
Looks like @clarkie made it for you here: https://github.com/sushijs/sydney-aus I've invited you as admin of the Sydney, Australia team, who admins that repository.

**Comment by terinjokes** [comment]
When you're ready, please open a PR to https://github.com/sushijs/sushijs.github.io
