### ISSUE TITLE
SushiJS Philadelphia

### ISSUE THREAD

**Issue by samuelcouch** [sushijs/meta#3]
Any interest? There are plenty of developers in the area!

**Comment by terinjokes** [comment]
@samuelcouch Get them to chatter support on this issue. :smile:

**Comment by terinjokes** [comment]
To reduce confusion going forward, I've borrowed BeerJS's readme and now have instructions. Quoting here:

---

Please open an issue on this repo and clearly state:
- **the github usernames of everyone who should be an admin on the repo**.
  We find that having at least 2 is best, but if it's just you, that's fine for now.
- **the name of the repo**.
  This becomes the URL slug, eg `sushijs/foo`. 
  If your city has a short name, like an airport code, that's fine.
  Whatever you like that's still recognizable as your city.

---
