### ISSUE TITLE
SushiJS Portland

### ISSUE THREAD

**Issue by thoward** [sushijs/meta#4]
Oh yes, I think it's time we brought this to Portland. 

/cc @adambaldwin @adron @aulvi @chrisdickinson @coderoshi @dlmanning @ednapiranha @hackygolucky @hallettj @jden @jerrysievert @kyledrake @lucperkins @mattly @meandavejustice @Merlyn @nvcexploder @phated @randallagordon @shanselman @wardcunningham @wraithan @zachbabb

**Comment by wraithan** [comment]
If we want to do train sushi, I recommend Sushi Ohana. Otherwise venue strongly depends on what we want our average cost to be.

**Comment by JerrySievert** [comment]
In.

**Comment by randallagordon** [comment]
Definitely! :thumbsup:

**Comment by evilpacket** [comment]
Yum. :thumbsup:

**Comment by hackygolucky** [comment]
If all it involves from me is hanging out with awesome people and eating
sushi, I'm in :)

**Comment by terinjokes** [comment]
Finally!

Can ya'll come to consensus for who I can consider point person for SushiJS PDX?

**Comment by nategeier** [comment]
In, Sushi Sakura has a great happy hour before 6, every plate is 2.50 I think.

**Comment by hackygolucky** [comment]
I vote @phated muahahaha

**Comment by wraithan** [comment]
@nategeier before 6 can be hard, lots of folks don't done with work until 5:30-6.

**Comment by thoward** [comment]
Yeah, before 6 might be hard. Sushi Sakura's prices are quite cheap,
though, even when not in happy hour. Also, it's centrally located, and
relatively large. Depending on the size of the group -- seating could be
challenging if we can't make a reservation.

I've always like Mio Sushi as well (there's a location at 13th/Hoyt in the
Pearl)... and Sushiland at 10th and Davis (near Powell's) is not a bad
option either.

... How frequently do we want to do this? I'm thinking once a month, on an
off day... like Tuesday or something.

**Comment by nvcexploder** [comment]
I'm in for once a month! :D

**Comment by junosuarez** [comment]
Okay, consulting http://whereis.jden.us, we can see that @jden will be in PDX from 06/23/2014 to 06/28/2014, so it would be awesome if we could have one during that time. Additionally, @jden will be in Portland for @cascadiajs from 07/26/2014 to 08/03/2014. So maybe we can have a cascadiajs edition sushijs?

**Comment by wraithan** [comment]
Sweet, sounds like @jden is organizer!

**Comment by terinjokes** [comment]
I'm not accepting @jden as organizer. He's already got the (eventual) SushiJS Chattanooga.

**Comment by junosuarez** [comment]
I prefer instigator to organizer

**Comment by hackygolucky** [comment]
Then I vote @horse_js

**Comment by Adron** [comment]
I'm in too. Am I late?  ;)

**Comment by dlmanning** [comment]
Can’t wait! Thanks for stepping up @jden.

**Comment by terinjokes** [comment]
Hey guys, just checking in. Any update on a organizer? Seems to be a lot of interest from folks, but no one stepping up.

**Comment by junosuarez** [comment]
This issue is still showing up on my personal "[open issues mentioning you](https://github.com/issues/mentioned)" list, limiting its utility. Could you please consider closing it?

**Comment by terinjokes** [comment]
Coming on a year old, granting the request. Please create a new issue if you want to put some sushi on it.
