### ISSUE TITLE
SushiJS Tokyo

### ISSUE THREAD

**Issue by watilde** [sushijs/meta#5]
Why don't you do that in Japan:exclamation:
Let's go :sushi: ≠(๑´ڡ`๑) ŧ‹”ŧ‹”

**Comment by kubosho** [comment]
:+1:

**Comment by grapswiz** [comment]
:+1:

**Comment by stelcheck** [comment]
:+1:

**Comment by terinjokes** [comment]
Any of this group interested in organizing this and being my point person?

**Comment by watilde** [comment]
@terinjokes Here! Actually there has already been a [similar culture](https://github.com/meta-sushi) in Tokyo/Japan and I've been there once. Potentially, some people are interested maybe.

**Comment by terinjokes** [comment]
To reduce confusion going forward, I've borrowed BeerJS's readme and now have instructions. Quoting here:

---

Please open an issue on this repo and clearly state:
- **the github usernames of everyone who should be an admin on the repo**.
  We find that having at least 2 is best, but if it's just you, that's fine for now.
- **the name of the repo**.
  This becomes the URL slug, eg `sushijs/foo`. 
  If your city has a short name, like an airport code, that's fine.
  Whatever you like that's still recognizable as your city.

---

@watilde if you're still interested, and can get another interested leader, I'd love to get SushiJS Tokyo started.

**Comment by okunokentaro** [comment]
:+1:

**Comment by ledsun** [comment]
:+1:

**Comment by kohei-takata** [comment]
:+1:

**Comment by watilde** [comment]
@terinjokes Thanks for the nice instructions! Ok, I understood how to chopstick SushiJS and still interesting to start it in Tokyo :smiley_cat: My clearly state is the following:
- Co-Admin: Add @tako-black please. He is also one of the nodeschool tokyo organizer member.
- The repository name: `tokyo-japan` is easily recognizable.

**Comment by terinjokes** [comment]
:sushi:!

I've added @tako-black and yourself to https://github.com/sushijs/tokyo-japan. Please fill free to borrow the README from the other repositories, and use the CODEOFCONDUCT template from this repo.
