### ISSUE TITLE
SushiJS Islamabad 

### ISSUE THREAD

**Issue by ghost** [sushijs/meta#6]
This is to spark interest in the idea of doing a SushiJS in Islamabad, Pakistan 👍

**Comment by terinjokes** [comment]
To reduce confusion going forward, I've borrowed BeerJS's readme and now have instructions. Quoting here:

---

Please open an issue on this repo and clearly state:
- **the github usernames of everyone who should be an admin on the repo**.
  We find that having at least 2 is best, but if it's just you, that's fine for now.
- **the name of the repo**.
  This becomes the URL slug, eg `sushijs/foo`. 
  If your city has a short name, like an airport code, that's fine.
  Whatever you like that's still recognizable as your city.

---

@itsnauman If you're still interested, and can get another interested leader, I'd love to get SushiJS Islamabad started.

**Comment by itsnauman** [comment]
@terinjokes It's only me for now :smiley:

**Comment by ghost** [comment]
@terinjokes I am moving to NYC in a few weeks. I'll start a Shushi JS fork in NYC :tada:
