### ISSUE TITLE
Chicago

### ISSUE THREAD

**Issue by clarknelson** [sushijs/meta#7]
Anyone interested in getting sushi and talking meteor/mongo/etc in Chicago?

**Comment by terinjokes** [comment]
@jailbot Have you had any success in getting anyone interested?

**Comment by clarknelson** [comment]
I know a few people who might want to do this, do you?

**Comment by terinjokes** [comment]
I usually look at issues for :+1:'s then figuring out who wants to be the organizer and then set them up with a repo + stickers.

**Comment by clarknelson** [comment]
It would be cool to be the organizer :)
How do you normally find people for events? I know a few outlets to try but do you have any suggestions?

**Comment by terinjokes** [comment]
I didn't do much advertising myself, I mostly just let it go through word of mouth through friends. Where in SF, it's not a large meetup, we average around 8 a month. We find that larger than about 10, and it starts to be hard to have a group conversation.

**Comment by terinjokes** [comment]
To reduce confusion going forward, I've borrowed BeerJS's readme and now have instructions. Quoting here:

---

Please open an issue on this repo and clearly state:
- **the github usernames of everyone who should be an admin on the repo**.
  We find that having at least 2 is best, but if it's just you, that's fine for now.
- **the name of the repo**.
  This becomes the URL slug, eg `sushijs/foo`. 
  If your city has a short name, like an airport code, that's fine.
  Whatever you like that's still recognizable as your city.

---

@jailbot If you're still interested, and can get another interested leader, I'd love to get SushiJS Chicago started.

**Comment by clarknelson** [comment]
yeah i'd love to do this ^.^
i'll look for another admin, but i'll post mine right now

**Comment by terinjokes** [comment]
`sushijs/chicago-il-usa` to match the current repos?

**Comment by clarknelson** [comment]
yeah sure sounds good

**Comment by clarknelson** [comment]
are there any plans for a real website? I can maybe help :)

**Comment by terinjokes** [comment]
@jailbot yeah, a designer friend of mine made one, I just never turn it into HTML+CSS. Soon™. :stuck_out_tongue: Let's take the discussion to the https://github.com/sushijs/sushijs.github.io repo.

You're now part of the Chicago, IL, USA team. You probably want to copy over the README and CODEOFCONDUCT to get started.

[SushiJS Chicago](https://github.com/sushijs/chicago-il-usa)
