### ISSUE TITLE
NYC

### ISSUE THREAD

**Issue by ghost** [sushijs/meta#9]
Hello :smiley: This is to spark interest of Shushi JS in NYC. 

It's currently only me for now. The repo's name should be `sushijs/nyc`

**Comment by terinjokes** [comment]
Also probably a whole bunch of BrooklynJS folks who would be interested.

**Comment by jeremiak** [comment]
Thanks for the ping @jden 

Sup, yall? I am a big fan of JavaScript though less of a fan of sushi. However, I always enjoy miso so def let me know if you get plans together :D

**Comment by ghost** [comment]
@jeremiak Sure! :smiley:

**Comment by reggi** [comment]
I'm Interested :) :fish: :sushi: :ramen: :doughnut:

**Comment by ghost** [comment]
@terinjokes Can we make a repo for Sushi JS NYC now?

**Comment by terinjokes** [comment]
@itsnauman `sushijs/new-york-ny-usa` or `sushijs/new-york-city-ny-us` or something else?

**Comment by ghost** [comment]
@terinjokes maybe `sushijs/nyc-usa`?

**Comment by indexzero** [comment]
@terinjokes `sushijs/new-york-ny-usa` seems consistent with the other names :+1:

**Comment by terinjokes** [comment]
Done.

**Comment by indexzero** [comment]
:smile: :sushi: :statue_of_liberty:
